bump_version: null
lint: null
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Nicolas Servant
  description: Analysis of Chromosome Conformation Capture data (Hi-C)
  force: false
  is_nfcore: true
  name: hic
  org: nf-core
  outdir: .
  skip_features: null
  version: 2.2.0dev
update: null
