nf_core_version: 3.1.0
repository_type: pipeline
template:
  author: Nicolas Servant
  description: Analysis of Chromosome Conformation Capture data (Hi-C)
  force: false
  is_nfcore: true
  name: hic
  org: nf-core
  outdir: .
  version: 2.2.0dev
